#!/bin/sh
# Copyright (c) 2026  Jason Self <j@jxself.org>
#
# This file is free software: you may copy, redistribute and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.  There is NO WARRANTY, to the extent permitted by law.
# See the GNU General Public License for more details:
# https://www.gnu.org/licenses/.
#
# Validate the C++/Qt exporters against the golden corpus in qt/tests/golden/.
# Every produced file must be byte-identical to the reference generated by the
# C# Trizbort exporters. Usage: sh qt/tests/run-golden.sh [path-to-trizbort-qt]

set -u

ROOT=$(cd "$(dirname "$0")/../.." && pwd)
BIN=${1:-"$ROOT/qt/build/trizbort-qt"}
GOLDEN="$ROOT/qt/tests/golden"
SAMPLES="$ROOT/samples"

export QT_QPA_PLATFORM=offscreen

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

# Formats the C++ app can currently export: "<extension>:<cli-flag>".
FORMATS="zil:--zil adv:--adventuron hug:--hugo i:--alan t:--tads inf:--inform6 ni:--inform7 aslx:--quest"

pass=0
fail=0

# Quest output embeds a fresh GUID (<gameid>) and the current year
# (<firstpublished>) on every run, so those two lines cannot be byte-matched.
# Canonicalize them before diffing; everything else must be byte-identical.
normalize() {
    if [ "$1" = "aslx" ]; then
        sed -e 's:<gameid>[^<]*</gameid>:<gameid>NORMALIZED</gameid>:' \
            -e 's:<firstpublished>[^<]*</firstpublished>:<firstpublished>NORMALIZED</firstpublished>:' \
            "$2"
    else
        cat "$2"
    fi
}

for m in "$SAMPLES"/*.trizbort; do
    base=$(basename "${m%.trizbort}")
    for fmt in $FORMATS; do
        ext=${fmt%%:*}
        flag=${fmt##*:}
        gold="$GOLDEN/$base/$base.$ext"
        [ -f "$gold" ] || continue
        out="$tmp/$base.$ext"
        if ! "$BIN" "$m" "$flag" "$out" >/dev/null 2>&1; then
            echo "FAIL (run)  $base.$ext"
            fail=$((fail + 1))
            continue
        fi
        normalize "$ext" "$gold" >"$tmp/gold.norm"
        normalize "$ext" "$out" >"$tmp/out.norm"
        if diff -q "$tmp/gold.norm" "$tmp/out.norm" >/dev/null 2>&1; then
            pass=$((pass + 1))
        else
            echo "FAIL (diff) $base.$ext"
            diff "$tmp/gold.norm" "$tmp/out.norm" | head -20
            fail=$((fail + 1))
        fi
    done
done

echo "golden corpus: PASS=$pass FAIL=$fail"
[ "$fail" -eq 0 ]
