"Zork_770614 main file"

<VERSION ZIP>
<CONSTANT RELEASEID 1>

"Main Loop"

<CONSTANT GAME-BANNER "Zork_770614|An interactive fiction by A Trizbort User">

<ROUTINE GO ()
    <CRLF> <CRLF>
    <TELL "" CR CR>
    <V-VERSION> <CRLF>
    <SETG HERE ,WEST-OF-HOUSE>
    <MOVE ,PLAYER ,HERE>
    <V-LOOK>
    <REPEAT ()
        <COND (<PARSER>
               <PERFORM ,PRSA ,PRSO ,PRSI>
               <COND (<NOT <GAME-VERB?>>
                      <APPLY <GETP ,HERE ,P?ACTION> ,M-END>
                      <CLOCKER>)>)>
        <SETG HERE <LOC ,WINNER>>>>

<INSERT-FILE "parser">

"Objects"

<ROOM WEST-OF-HOUSE
    (DESC "West of House")
    (IN ROOMS)
    (NORTH TO NORTH-OF-HOUSE)
    (SOUTH TO SOUTH-OF-HOUSE)
    (WEST TO FOREST-2)
    (FLAGS LIGHTBIT)>


<ROOM SOUTH-OF-HOUSE
    (DESC "South of House")
    (IN ROOMS)
    (SOUTH TO FOREST-1)
    (EAST TO BEHIND-HOUSE)
    (WEST TO WEST-OF-HOUSE)
    (FLAGS LIGHTBIT)>


<ROOM BEHIND-HOUSE
    (DESC "Behind House")
    (IN ROOMS)
    (NORTH TO NORTH-OF-HOUSE)
    (SOUTH TO SOUTH-OF-HOUSE)
    (EAST TO CLEARING)
    (WEST PER TRIZBORT-CONDITIONAL-EXIT)
    (FLAGS LIGHTBIT)>


<ROUTINE TRIZBORT-CONDITIONAL-EXIT ()
    <TELL "An export nymph appears on your keyboard. She says, 'You can't go that way, as that exit was marked as conditional, you know, a dotted line, in Trizbort. Obviously in your game you'll have a better rationale for this than, er, me.' She looks embarrassed. 'Bye!'" CR>
    <RFALSE>>


<OBJECT SMALL-WINDOW
    (IN BEHIND-HOUSE)
    (DESC "Small window")
    (SYNONYM WINDOW)
    (ADJECTIVE SMALL)
    (FLAGS TAKEBIT)>


<ROOM NORTH-OF-HOUSE
    (DESC "North of House")
    (IN ROOMS)
    (NORTH TO FOREST-3)
    (EAST TO BEHIND-HOUSE)
    (WEST TO WEST-OF-HOUSE)
    (FLAGS LIGHTBIT)>


<ROOM CLEARING
    (DESC "Clearing")
    (IN ROOMS)
    (SOUTH TO FOREST-1)
    (WEST TO FOREST-3)
    (SW TO BEHIND-HOUSE)
    (FLAGS LIGHTBIT)>


<OBJECT PILE-OF-LEAVES
    (IN CLEARING)
    (DESC "Pile of leaves")
    (SYNONYM LEAVES)
    (ADJECTIVE PILE OF)
    (FLAGS TAKEBIT)>


<ROOM KITCHEN
    (DESC "Kitchen")
    (IN ROOMS)
    (EAST PER TRIZBORT-CONDITIONAL-EXIT)
    (WEST TO LIVING-ROOM)
    (UP TO ATTIC)
    (FLAGS LIGHTBIT)>


<OBJECT BOTTLE
    (IN KITCHEN)
    (DESC "Bottle")
    (SYNONYM BOTTLE)
    (FLAGS TAKEBIT)>


<OBJECT SACK
    (IN KITCHEN)
    (DESC "Sack")
    (SYNONYM SACK)
    (FLAGS TAKEBIT)>


<ROOM LIVING-ROOM
    (DESC "Living Room")
    (IN ROOMS)
    (EAST TO KITCHEN)
    (FLAGS LIGHTBIT)>


<OBJECT TROPGY-CASE
    (IN LIVING-ROOM)
    (DESC "Tropgy case")
    (SYNONYM CASE)
    (ADJECTIVE TROPGY)
    (FLAGS TAKEBIT)>


<OBJECT LANTERN
    (IN LIVING-ROOM)
    (DESC "Lantern")
    (SYNONYM LANTERN)
    (FLAGS TAKEBIT)>


<OBJECT RUG
    (IN LIVING-ROOM)
    (DESC "Rug")
    (SYNONYM RUG)
    (FLAGS TAKEBIT)>


<ROOM ATTIC
    (DESC "Attic")
    (IN ROOMS)
    (DOWN TO KITCHEN)
    (FLAGS LIGHTBIT)>


<OBJECT ROPE
    (IN ATTIC)
    (DESC "Rope")
    (SYNONYM ROPE)
    (FLAGS TAKEBIT)>


<OBJECT KNIFE
    (IN ATTIC)
    (DESC "Knife")
    (SYNONYM KNIFE)
    (FLAGS TAKEBIT)>


<ROOM FOREST-1
    (DESC "Forest 1")
    (IN ROOMS)
    (NORTH TO SOUTH-OF-HOUSE)
    (EAST TO CLEARING)
    (WEST TO FOREST-2)
    (FLAGS LIGHTBIT)>


<ROOM FOREST-2
    (DESC "Forest 2")
    (IN ROOMS)
    (EAST TO FOREST-3)
    (FLAGS LIGHTBIT)>


<ROOM FOREST-3
    (DESC "Forest 3")
    (IN ROOMS)
    (SOUTH TO CLEARING)
    (EAST TO CLEARING)
    (WEST TO NORTH-OF-HOUSE)
    (FLAGS LIGHTBIT)>


<ROOM CELLAR
    (DESC "Cellar")
    (IN ROOMS)
    (SOUTH TO WEST-OF-CHASM)
    (EAST TO TROLL-ROOM)
    (FLAGS LIGHTBIT)>


<ROOM WEST-OF-CHASM
    (DESC "West of Chasm")
    (IN ROOMS)
    (NORTH TO NORTH-SOUTH-CRAWLWAY)
    (SOUTH TO GALLERY)
    (WEST TO CELLAR)
    (FLAGS LIGHTBIT)>


<ROOM GALLERY
    (DESC "Gallery")
    (IN ROOMS)
    (NORTH TO WEST-OF-CHASM)
    (SOUTH TO STUDIO)
    (FLAGS LIGHTBIT)>


<OBJECT PAINTING
    (IN GALLERY)
    (DESC "Painting")
    (SYNONYM PAINTING)
    (FLAGS TAKEBIT)>


<ROOM STUDIO
    (DESC "Studio")
    (IN ROOMS)
    (NORTH TO NORTH-SOUTH-CRAWLWAY)
    (NW TO GALLERY)
    (FLAGS LIGHTBIT)>


<OBJECT CHIMNEY
    (IN STUDIO)
    (DESC "Chimney")
    (SYNONYM CHIMNEY)
    (FLAGS TAKEBIT)>


<ROOM NORTH-SOUTH-CRAWLWAY
    (DESC "North-South Crawlway")
    (IN ROOMS)
    (NORTH TO WEST-OF-CHASM)
    (SOUTH TO STUDIO)
    (EAST TO TROLL-ROOM)
    (FLAGS LIGHTBIT)>


<ROOM TROLL-ROOM
    (DESC "Troll Room")
    (IN ROOMS)
    (NORTH TO EAST-WEST-PASSAGE)
    (EAST TO NORTH-SOUTH-CRAWLWAY)
    (WEST TO CELLAR)
    (FLAGS LIGHTBIT)>


<OBJECT TROLL
    (IN TROLL-ROOM)
    (DESC "Troll")
    (SYNONYM TROLL)
    (FLAGS TAKEBIT)>


<ROOM EAST-WEST-PASSAGE
    (DESC "East-West Passage")
    (IN ROOMS)
    (NORTH TO DEEP-RAVINE)
    (EAST TO ROUND-ROOM)
    (WEST TO TROLL-ROOM)
    (FLAGS LIGHTBIT)>


<ROOM CYCLOPS-ROOM
    (DESC "Cyclops Room")
    (IN ROOMS)
    (UP TO TREASURE-ROOM)
    (FLAGS LIGHTBIT)>


<OBJECT CYCLOP
    (IN CYCLOPS-ROOM)
    (DESC "Cyclop")
    (SYNONYM CYCLOP)
    (FLAGS TAKEBIT)>


<ROOM STRANGE-PASSAGE
    (DESC "Strange Passage")
    (IN ROOMS)
    (FLAGS LIGHTBIT)>


<ROOM TREASURE-ROOM
    (DESC "Treasure Room")
    (IN ROOMS)
    (DOWN TO CYCLOPS-ROOM)
    (FLAGS LIGHTBIT)>


<OBJECT THIEF
    (IN TREASURE-ROOM)
    (DESC "Thief")
    (SYNONYM THIEF)
    (FLAGS TAKEBIT)>


<OBJECT CHALICE
    (IN TREASURE-ROOM)
    (DESC "Chalice")
    (SYNONYM CHALICE)
    (FLAGS TAKEBIT)>


<ROOM DOME-ROOM
    (DESC "Dome Room")
    (IN ROOMS)
    (EAST TO ROCKY-CRAWL)
    (DOWN PER TRIZBORT-CONDITIONAL-EXIT)
    (FLAGS LIGHTBIT)>


<OBJECT RAILING
    (IN DOME-ROOM)
    (DESC "Railing")
    (SYNONYM RAILING)
    (FLAGS TAKEBIT)>


<ROOM ROCKY-CRAWL
    (DESC "Rocky Crawl")
    (IN ROOMS)
    (EAST TO DOME-ROOM)
    (WEST TO DEEP-RAVINE)
    (NW TO EGYPTIAN-ROOM)
    (FLAGS LIGHTBIT)>


<ROOM DEEP-RAVINE
    (DESC "Deep Ravine")
    (IN ROOMS)
    (SOUTH TO EAST-WEST-PASSAGE)
    (EAST TO CHASM)
    (WEST TO ROCKY-CRAWL)
    (DOWN TO RESERVOIR-SOUTH)
    (FLAGS LIGHTBIT)>


<ROOM CHASM
    (DESC "Chasm")
    (IN ROOMS)
    (SOUTH TO DEEP-RAVINE)
    (EAST TO NORTH-SOUTH-PASSAGE)
    (FLAGS LIGHTBIT)>


<ROOM NORTH-SOUTH-PASSAGE
    (DESC "North-South Passage")
    (IN ROOMS)
    (NORTH TO CHASM)
    (SOUTH TO ROUND-ROOM)
    (NE TO LOUD-ROOM)
    (FLAGS LIGHTBIT)>


<ROOM LOUD-ROOM
    (DESC "Loud Room")
    (IN ROOMS)
    (EAST TO ANCIENT-CHASM)
    (WEST TO NORTH-SOUTH-PASSAGE)
    (UP TO -DAMP-CAVE)
    (FLAGS LIGHTBIT)>


<OBJECT PLATINUM-BAR
    (IN LOUD-ROOM)
    (DESC "Platinum Bar")
    (SYNONYM BAR)
    (ADJECTIVE PLATINUM)
    (FLAGS TAKEBIT)>


<ROOM ROUND-ROOM
    (DESC "Round Room")
    (IN ROOMS)
    (FLAGS LIGHTBIT)>


<ROOM EGYPTIAN-ROOM
    (DESC "Egyptian Room")
    (IN ROOMS)
    (EAST TO ROCKY-CRAWL)
    (WEST TO GLACIER-ROOM)
    (FLAGS LIGHTBIT)>


<OBJECT GOLD-COFFIN
    (IN EGYPTIAN-ROOM)
    (DESC "Gold Coffin")
    (SYNONYM COFFIN)
    (ADJECTIVE GOLD)
    (FLAGS TAKEBIT)>


<ROOM GLACIER-ROOM
    (DESC "Glacier Room")
    (IN ROOMS)
    (NORTH TO STREAM-VIEW)
    (EAST TO EGYPTIAN-ROOM)
    (WEST PER TRIZBORT-CONDITIONAL-EXIT)
    (FLAGS LIGHTBIT)>


<OBJECT ICE
    (IN GLACIER-ROOM)
    (DESC "Ice")
    (SYNONYM ICE)
    (FLAGS TAKEBIT VOWELBIT)>


<ROOM STREAM-VIEW
    (DESC "Stream View")
    (IN ROOMS)
    (NORTH TO GLACIER-ROOM)
    (EAST TO RESERVOIR-SOUTH)
    (FLAGS LIGHTBIT)>


<ROOM RESERVOIR-SOUTH
    (DESC "Reservoir South")
    (IN ROOMS)
    (NORTH PER TRIZBORT-CONDITIONAL-EXIT)
    (SOUTH TO DEEP-RAVINE)
    (WEST TO STREAM-VIEW)
    (UP TO DEEP-CANYON)
    (FLAGS LIGHTBIT)>


<OBJECT ROPE2
    (IN RESERVOIR-SOUTH)
    (DESC "Rope")
    (SYNONYM ROPE)
    (FLAGS TAKEBIT)>


<OBJECT TRUNK-WITH-JEWELS
    (IN RESERVOIR-SOUTH)
    (DESC "Trunk with Jewels")
    (SYNONYM JEWELS)
    (ADJECTIVE TRUNK WITH)
    (FLAGS TAKEBIT)>


<ROOM DEEP-CANYON
    (DESC "Deep Canyon")
    (IN ROOMS)
    (EAST TO DAM)
    (SE TO RESERVOIR-SOUTH)
    (FLAGS LIGHTBIT)>


<ROOM TORCH-ROOM
    (DESC "Torch Room")
    (IN ROOMS)
    (FLAGS LIGHTBIT)>


<OBJECT TORCH
    (IN TORCH-ROOM)
    (DESC "Torch")
    (SYNONYM TORCH)
    (FLAGS TAKEBIT)>


<ROOM DAM
    (DESC "Dam")
    (IN ROOMS)
    (NORTH TO DAM-LOBBY)
    (SOUTH TO DEEP-CANYON)
    (EAST TO -DAMP-CAVE)
    (FLAGS LIGHTBIT)>


<ROOM -DAMP-CAVE
    (DESC " Damp Cave")
    (IN ROOMS)
    (SOUTH TO LOUD-ROOM)
    (EAST TO DAM)
    (FLAGS LIGHTBIT)>


<OBJECT SMALL-CRACK
    (IN -DAMP-CAVE)
    (DESC "Small Crack")
    (SYNONYM CRACK)
    (ADJECTIVE SMALL)
    (FLAGS TAKEBIT)>


<ROOM DAM-LOBBY
    (DESC "Dam Lobby")
    (IN ROOMS)
    (NORTH TO MAINTENANCE-ROOM)
    (SOUTH TO DAM)
    (EAST TO MAINTENANCE-ROOM)
    (FLAGS LIGHTBIT)>


<OBJECT MATCHBOOK
    (IN DAM-LOBBY)
    (DESC "Matchbook")
    (SYNONYM MATCHBOOK)
    (FLAGS TAKEBIT)>


<OBJECT GUIDEBOOKS
    (IN DAM-LOBBY)
    (DESC "Guidebooks")
    (SYNONYM GUIDEBOOKS)
    (FLAGS TAKEBIT)>


<ROOM MAINTENANCE-ROOM
    (DESC "Maintenance Room")
    (IN ROOMS)
    (SOUTH TO DAM-LOBBY)
    (WEST TO DAM-LOBBY)
    (FLAGS LIGHTBIT)>


<OBJECT TUBE-OF-TOOTHPASTE
    (IN MAINTENANCE-ROOM)
    (DESC "Tube of toothpaste")
    (SYNONYM TOOTHPASTE)
    (ADJECTIVE TUBE OF)
    (FLAGS TAKEBIT)>


<OBJECT WRENCH
    (IN MAINTENANCE-ROOM)
    (DESC "Wrench")
    (SYNONYM WRENCH)
    (FLAGS TAKEBIT)>


<OBJECT SCREWDRIVER
    (IN MAINTENANCE-ROOM)
    (DESC "Screwdriver")
    (SYNONYM SCREWDRIVER)
    (FLAGS TAKEBIT)>


<ROOM ANCIENT-CHASM
    (DESC "Ancient Chasm")
    (IN ROOMS)
    (NORTH TO DEAD-END-2)
    (SOUTH TO LOUD-ROOM)
    (WEST TO DEAD-END)
    (FLAGS LIGHTBIT)>


<ROOM RESERVOIR-NORTH
    (DESC "Reservoir North")
    (IN ROOMS)
    (NORTH TO ATLANTIS-ROOM)
    (SOUTH PER TRIZBORT-CONDITIONAL-EXIT)
    (FLAGS LIGHTBIT)>


<ROOM ATLANTIS-ROOM
    (DESC "Atlantis Room")
    (IN ROOMS)
    (SE TO RESERVOIR-NORTH)
    (UP TO CAVE)
    (FLAGS LIGHTBIT)>


<OBJECT TRIDENT
    (IN ATLANTIS-ROOM)
    (DESC "Trident")
    (SYNONYM TRIDENT)
    (FLAGS TAKEBIT)>


<ROOM CAVE
    (DESC "Cave")
    (IN ROOMS)
    (NORTH TO MIRROR-ROOM)
    (DOWN TO ATLANTIS-ROOM)
    (FLAGS LIGHTBIT)>


<ROOM MIRROR-ROOM
    (DESC "Mirror Room")
    (IN ROOMS)
    (NORTH TO STEEP-CRAWLWAY)
    (EAST TO CAVE)
    (WEST TO COLD-PASSAGE)
    (FLAGS LIGHTBIT)>


<ROOM COLD-PASSAGE
    (DESC "Cold Passage")
    (IN ROOMS)
    (NORTH TO STEEP-CRAWLWAY)
    (EAST TO MIRROR-ROOM)
    (WEST TO SLIDE-ROOM)
    (FLAGS LIGHTBIT)>


<ROOM STEEP-CRAWLWAY
    (DESC "Steep Crawlway")
    (IN ROOMS)
    (SOUTH TO MIRROR-ROOM)
    (SW TO COLD-PASSAGE)
    (FLAGS LIGHTBIT)>


<ROOM SLIDE-ROOM
    (DESC "Slide Room")
    (IN ROOMS)
    (EAST TO COLD-PASSAGE)
    (DOWN TO CELLAR)
    (FLAGS LIGHTBIT)>


<ROOM ENTRANCE-TO-HADES
    (DESC "*Entrance to Hades")
    (IN ROOMS)
    (EAST PER TRIZBORT-CONDITIONAL-EXIT)
    (UP TO CAVE-2)
    (FLAGS LIGHTBIT)>


<OBJECT EVIL-SPIRITS
    (IN ENTRANCE-TO-HADES)
    (DESC "Evil Spirits")
    (SYNONYM SPIRITS)
    (ADJECTIVE EVIL)
    (FLAGS TAKEBIT VOWELBIT)>


<ROOM NARROW-CRAWLWAY
    (DESC "Narrow Crawlway")
    (IN ROOMS)
    (NORTH TO GRAIL-ROOM)
    (SOUTH TO CAVE-2)
    (SW TO MIRROR-ROOM-2)
    (FLAGS LIGHTBIT)>


<ROOM GRAIL-ROOM
    (DESC "Grail Room")
    (IN ROOMS)
    (EAST TO NARROW-CRAWLWAY)
    (WEST PER TRIZBORT-CONDITIONAL-EXIT)
    (UP TO TEMPLE)
    (FLAGS LIGHTBIT)>


<OBJECT GRAIL
    (IN GRAIL-ROOM)
    (DESC "Grail")
    (SYNONYM GRAIL)
    (FLAGS TAKEBIT)>


<ROOM ROUND-ROOM-2
    (DESC "Round Room")
    (IN ROOMS)
    (NORTH PER TRIZBORT-CONDITIONAL-EXIT)
    (SOUTH PER TRIZBORT-CONDITIONAL-EXIT)
    (EAST PER TRIZBORT-CONDITIONAL-EXIT)
    (WEST PER TRIZBORT-CONDITIONAL-EXIT)
    (NE PER TRIZBORT-CONDITIONAL-EXIT)
    (SW PER TRIZBORT-CONDITIONAL-EXIT)
    (NW PER TRIZBORT-CONDITIONAL-EXIT)
    (FLAGS LIGHTBIT)>


<ROOM EAST-WEST-PASSAGE-2
    (DESC "East-West Passage")
    (IN ROOMS)
    (EAST PER TRIZBORT-CONDITIONAL-EXIT)
    (FLAGS LIGHTBIT)>


<ROOM NORTH-SOUTH-PASSAGE-2
    (DESC "North-South Passage")
    (IN ROOMS)
    (SE PER TRIZBORT-CONDITIONAL-EXIT)
    (FLAGS LIGHTBIT)>


<ROOM WINDING-PASSAGE
    (DESC "Winding Passage")
    (IN ROOMS)
    (NORTH PER TRIZBORT-CONDITIONAL-EXIT)
    (EAST TO MIRROR-ROOM-2)
    (FLAGS LIGHTBIT)>


<ROOM MIRROR-ROOM-2
    (DESC "Mirror Room")
    (IN ROOMS)
    (NORTH TO NARROW-CRAWLWAY)
    (EAST TO CAVE-2)
    (WEST TO WINDING-PASSAGE)
    (FLAGS LIGHTBIT)>


<OBJECT MIRROR
    (IN MIRROR-ROOM-2)
    (DESC "Mirror")
    (SYNONYM MIRROR)
    (FLAGS TAKEBIT)>


<ROOM CAVE-2
    (DESC "Cave")
    (IN ROOMS)
    (NORTH TO NARROW-CRAWLWAY)
    (WEST TO MIRROR-ROOM-2)
    (DOWN TO ENTRANCE-TO-HADES)
    (FLAGS LIGHTBIT)>


<ROOM DEEP-CANYON-2
    (DESC "Deep Canyon")
    (IN ROOMS)
    (SOUTH PER TRIZBORT-CONDITIONAL-EXIT)
    (FLAGS LIGHTBIT)>


<ROOM MAZE
    (DESC "Maze")
    (IN ROOMS)
    (SW PER TRIZBORT-CONDITIONAL-EXIT)
    (FLAGS LIGHTBIT)>


<ROOM ENGRAVINGS-CAVE
    (DESC "Engravings Cave")
    (IN ROOMS)
    (NORTH PER TRIZBORT-CONDITIONAL-EXIT)
    (SE TO RIDDLE-ROOM)
    (FLAGS LIGHTBIT)>


<OBJECT ENGRAVINGS
    (IN ENGRAVINGS-CAVE)
    (DESC "Engravings")
    (SYNONYM ENGRAVINGS)
    (FLAGS TAKEBIT VOWELBIT)>


<ROOM RIDDLE-ROOM
    (DESC "Riddle Room")
    (IN ROOMS)
    (EAST PER TRIZBORT-CONDITIONAL-EXIT)
    (DOWN TO ENGRAVINGS-CAVE)
    (FLAGS LIGHTBIT)>


<ROOM PEARL-ROOM
    (DESC "Pearl Room")
    (IN ROOMS)
    (WEST PER TRIZBORT-CONDITIONAL-EXIT)
    (FLAGS LIGHTBIT)>


<OBJECT PEARL-NECKLACE
    (IN PEARL-ROOM)
    (DESC "Pearl Necklace")
    (SYNONYM NECKLACE)
    (ADJECTIVE PEARL)
    (FLAGS TAKEBIT)>


<ROOM TEMPLE
    (DESC "Temple")
    (IN ROOMS)
    (EAST TO ALTAR)
    (WEST TO GRAIL-ROOM)
    (FLAGS LIGHTBIT)>


<OBJECT BRASS-BELL
    (IN TEMPLE)
    (DESC "Brass bell")
    (SYNONYM BELL)
    (ADJECTIVE BRASS)
    (FLAGS TAKEBIT)>


<ROOM ALTAR
    (DESC "Altar")
    (IN ROOMS)
    (WEST TO TEMPLE)
    (FLAGS LIGHTBIT)>


<OBJECT BLACK-BOOK
    (IN ALTAR)
    (DESC "Black Book")
    (SYNONYM BOOK)
    (ADJECTIVE BLACK)
    (FLAGS TAKEBIT)>


<OBJECT CANDLES
    (IN ALTAR)
    (DESC "Candles")
    (SYNONYM CANDLES)
    (FLAGS TAKEBIT)>


<ROOM DEAD-END
    (DESC "Dead End")
    (IN ROOMS)
    (EAST TO ANCIENT-CHASM)
    (FLAGS LIGHTBIT)>


<ROOM DEAD-END-2
    (DESC "Dead End")
    (IN ROOMS)
    (SW TO ANCIENT-CHASM)
    (FLAGS LIGHTBIT)>


<ROOM LAND-OF-THE-LIVING-DEAD
    (DESC "Land of the Living Dead")
    (IN ROOMS)
    (WEST PER TRIZBORT-CONDITIONAL-EXIT)
    (FLAGS LIGHTBIT)>


<ROOM RUBY-ROOM
    (DESC "Ruby Room")
    (IN ROOMS)
    (SOUTH PER TRIZBORT-CONDITIONAL-EXIT)
    (FLAGS LIGHTBIT)>


<OBJECT RUBY
    (IN RUBY-ROOM)
    (DESC "Ruby")
    (SYNONYM RUBY)
    (FLAGS TAKEBIT)>

