"Leadlight Gamma Map main file"

<VERSION ZIP>
<CONSTANT RELEASEID 1>

"Main Loop"

<CONSTANT GAME-BANNER "Leadlight Gamma Map|An interactive fiction by Andrew Schultz">

<ROUTINE GO ()
    <CRLF> <CRLF>
    <TELL "Map of Wade Clarke's 2010 game Leadlight (and its Inform port Leadlight Gamma). Orange=dorm grey=library purple=indoor yellow=inner sanctum red=inner inner sanctum" CR CR>
    <V-VERSION> <CRLF>
    <SETG HERE ,LINVILLE-STUDENT-LIBRARY>
    <MOVE ,PLAYER ,HERE>
    <V-LOOK>
    <REPEAT ()
        <COND (<PARSER>
               <PERFORM ,PRSA ,PRSO ,PRSI>
               <COND (<NOT <GAME-VERB?>>
                      <APPLY <GETP ,HERE ,P?ACTION> ,M-END>
                      <CLOCKER>)>)>
        <SETG HERE <LOC ,WINNER>>>>

<INSERT-FILE "parser">

"Objects"

<ROOM LINVILLE-STUDENT-LIBRARY
    (DESC "Linville Student Library")
    (IN ROOMS)
    (SOUTH TO AMONGST-THE-LIBRARY-STACKS)
    (EAST TO IN-THE-LIBRARY-FOYER)
    (WEST TO LIBRARY-TOILET)
    (FLAGS LIGHTBIT)>


<OBJECT CHARLOTTE-JEFFS
    (IN LINVILLE-STUDENT-LIBRARY)
    (DESC "Charlotte Jeffs")
    (SYNONYM JEFFS)
    (ADJECTIVE CHARLOTTE)
    (FLAGS TAKEBIT)>


<ROOM LIBRARY-TOILET
    (DESC "Library Toilet")
    (IN ROOMS)
    (EAST TO LINVILLE-STUDENT-LIBRARY)
    (FLAGS LIGHTBIT)>


<ROOM AMONGST-THE-LIBRARY-STACKS
    (DESC "Amongst the Library Stacks")
    (IN ROOMS)
    (NORTH TO LINVILLE-STUDENT-LIBRARY)
    (FLAGS LIGHTBIT)>


<ROOM IN-THE-LIBRARY-FOYER
    (DESC "In the Library Foyer")
    (IN ROOMS)
    (EAST PER TRIZBORT-CONDITIONAL-EXIT)
    (WEST TO LINVILLE-STUDENT-LIBRARY)
    (FLAGS LIGHTBIT)>


<ROUTINE TRIZBORT-CONDITIONAL-EXIT ()
    <TELL "An export nymph appears on your keyboard. She says, 'You can't go that way, as that exit was marked as conditional, you know, a dotted line, in Trizbort. Obviously in your game you'll have a better rationale for this than, er, me.' She looks embarrassed. 'Bye!'" CR>
    <RFALSE>>


<OBJECT NARELLE-PARKER
    (IN IN-THE-LIBRARY-FOYER)
    (DESC "Narelle Parker")
    (SYNONYM PARKER)
    (ADJECTIVE NARELLE)
    (FLAGS TAKEBIT)>


<ROOM IN-THE-QUADRANGLE
    (DESC "In the Quadrangle")
    (IN ROOMS)
    (NORTH TO ON-THE-SCHOOL-STEPS)
    (SOUTH TO ON-THE-ROSE-GARDEN-LAWN)
    (EAST TO IN-THE-DORMITORY-COURTYARD)
    (WEST PER TRIZBORT-CONDITIONAL-EXIT)
    (FLAGS LIGHTBIT)>


<ROOM ON-THE-ROSE-GARDEN-LAWN
    (DESC "On the Rose Garden Lawn")
    (IN ROOMS)
    (NORTH TO IN-THE-QUADRANGLE)
    (FLAGS LIGHTBIT)>


<OBJECT ALEXIS-KARPA
    (IN ON-THE-ROSE-GARDEN-LAWN)
    (DESC "Alexis Karpa")
    (SYNONYM KARPA)
    (ADJECTIVE ALEXIS)
    (FLAGS TAKEBIT VOWELBIT)>


<ROOM IN-THE-DORMITORY-COURTYARD
    (DESC "In the Dormitory Courtyard")
    (IN ROOMS)
    (SOUTH TO IN-THE-GYM-ENTRY)
    (EAST TO IN-THE-DORMITORY-ENTRYWAY)
    (WEST TO IN-THE-QUADRANGLE)
    (FLAGS LIGHTBIT)>


<ROOM IN-THE-GYM-ENTRY
    (DESC "In the Gym Entry")
    (IN ROOMS)
    (NORTH TO IN-THE-DORMITORY-COURTYARD)
    (SOUTH TO ON-THE-GYM-COURT-NORTH)
    (FLAGS LIGHTBIT)>


<ROOM ON-THE-GYM-COURT-NORTH
    (DESC "On the Gym Court, North")
    (IN ROOMS)
    (NORTH TO IN-THE-GYM-ENTRY)
    (SOUTH PER TRIZBORT-CONDITIONAL-EXIT)
    (UP TO IN-THE-UPSTAIRS-CHANGING-ROOM)
    (FLAGS LIGHTBIT)>


<ROOM ON-THE-GYM-COURT-SOUTH
    (DESC "On the Gym Court, South")
    (IN ROOMS)
    (NORTH PER TRIZBORT-CONDITIONAL-EXIT)>


<ROOM IN-THE-DORMITORY-ENTRYWAY
    (DESC "In the Dormitory Entryway")
    (IN ROOMS)
    (NORTH TO ROOM-106)
    (SOUTH TO ROOM-101)
    (EAST PER TRIZBORT-CONDITIONAL-EXIT)
    (WEST TO IN-THE-DORMITORY-COURTYARD)
    (FLAGS LIGHTBIT)>


<OBJECT MS-PALMERDIANE-FALLON
    (IN IN-THE-DORMITORY-ENTRYWAY)
    (DESC "Ms Palmer/Diane Fallon")
    (SYNONYM FALLON)
    (ADJECTIVE MS PALMERDIANE)
    (FLAGS TAKEBIT)>


<ROOM ROOM-106
    (DESC "Room 106")
    (IN ROOMS)
    (SOUTH TO IN-THE-DORMITORY-ENTRYWAY)
    (FLAGS LIGHTBIT)>


<ROOM ROOM-101
    (DESC "Room 101")
    (IN ROOMS)
    (NORTH TO IN-THE-DORMITORY-ENTRYWAY)
    (FLAGS LIGHTBIT)>


<OBJECT SHERYL-BOURKE
    (IN ROOM-101)
    (DESC "Sheryl Bourke")
    (SYNONYM BOURKE)
    (ADJECTIVE SHERYL)
    (FLAGS TAKEBIT)>


<ROOM HALFWAY-ALONG-THE-DORM-HALL
    (DESC "Halfway Along the Dorm Hall")
    (IN ROOMS)
    (NORTH PER TRIZBORT-CONDITIONAL-EXIT)
    (SOUTH TO ROOM-102)
    (EAST TO AT-THE-DORM-HALLS-EAST-END)
    (WEST PER TRIZBORT-CONDITIONAL-EXIT)
    (FLAGS LIGHTBIT)>


<ROOM ROOM-105
    (DESC "Room 105")
    (IN ROOMS)
    (SOUTH PER TRIZBORT-CONDITIONAL-EXIT)
    (FLAGS LIGHTBIT)>


<ROOM ROOM-102
    (DESC "Room 102")
    (IN ROOMS)
    (NORTH TO HALFWAY-ALONG-THE-DORM-HALL)
    (FLAGS LIGHTBIT)>


<OBJECT LOUISE
    (IN ROOM-102)
    (DESC "Louise")
    (SYNONYM LOUISE)
    (FLAGS TAKEBIT)>


<ROOM AT-THE-DORM-HALLS-EAST-END
    (DESC "At the Dorm Hall's East End")
    (IN ROOMS)
    (NORTH TO ROOM-104)
    (SOUTH TO ROOM-103)
    (WEST TO HALFWAY-ALONG-THE-DORM-HALL)
    (FLAGS LIGHTBIT)>


<ROOM ROOM-104
    (DESC "Room 104")
    (IN ROOMS)
    (SOUTH TO AT-THE-DORM-HALLS-EAST-END)
    (FLAGS LIGHTBIT)>


<ROOM ROOM-103
    (DESC "Room 103")
    (IN ROOMS)
    (NORTH TO AT-THE-DORM-HALLS-EAST-END)
    (FLAGS LIGHTBIT)>


<ROOM ON-THE-SCHOOL-STEPS
    (DESC "On the School Steps")
    (IN ROOMS)
    (NORTH PER TRIZBORT-CONDITIONAL-EXIT)
    (SOUTH TO IN-THE-QUADRANGLE)
    (EAST TO ON-THE-TRELLISED-PATIO)
    (WEST TO BY-THE-SCHOOL-FOUNTAIN)
    (FLAGS LIGHTBIT)>


<ROOM IN-THE-SCHOOL-FOYER
    (DESC "In the School Foyer")
    (IN ROOMS)
    (NORTH TO IN-THE-MARBLE-STATEROOM)
    (SOUTH PER TRIZBORT-CONDITIONAL-EXIT)
    (EAST TO IN-THE-SICK-BAY)
    (WEST TO IN-THE-RECEPTIONISTS-OFFICE)
    (FLAGS LIGHTBIT)>


<ROOM ON-THE-TRELLISED-PATIO
    (DESC "On the Trellised Patio")
    (IN ROOMS)
    (WEST TO ON-THE-SCHOOL-STEPS)
    (FLAGS LIGHTBIT)>


<OBJECT GARDENER
    (IN ON-THE-TRELLISED-PATIO)
    (DESC "Gardener")
    (SYNONYM GARDENER)
    (FLAGS TAKEBIT)>


<ROOM BY-THE-SCHOOL-FOUNTAIN
    (DESC "By the School Fountain")
    (IN ROOMS)
    (NORTH TO IN-THE-ART-COTTAGE)
    (SOUTH TO IN-STAFF-COTTAGE-B)
    (EAST TO ON-THE-SCHOOL-STEPS)
    (FLAGS LIGHTBIT)>


<OBJECT MYSTERY-GIRL
    (IN BY-THE-SCHOOL-FOUNTAIN)
    (DESC "Mystery Girl")
    (SYNONYM GIRL)
    (ADJECTIVE MYSTERY)
    (FLAGS TAKEBIT)>


<ROOM IN-THE-ART-COTTAGE
    (DESC "In the Art Cottage")
    (IN ROOMS)
    (SOUTH TO BY-THE-SCHOOL-FOUNTAIN)
    (FLAGS LIGHTBIT)>


<OBJECT MR-RHODES
    (IN IN-THE-ART-COTTAGE)
    (DESC "Mr Rhodes")
    (SYNONYM RHODES)
    (ADJECTIVE MR)
    (FLAGS TAKEBIT)>


<ROOM IN-STAFF-COTTAGE-B
    (DESC "In Staff Cottage B")
    (IN ROOMS)
    (NORTH TO BY-THE-SCHOOL-FOUNTAIN)
    (FLAGS LIGHTBIT)>


<OBJECT FILE-MISS-ARDEN
    (IN IN-STAFF-COTTAGE-B)
    (DESC "File (Miss Arden)")
    (SYNONYM ARDEN)
    (ADJECTIVE FILE MISS)
    (FLAGS TAKEBIT)>


<ROOM IN-THE-RECEPTIONISTS-OFFICE
    (DESC "In the Receptionist's Office")
    (IN ROOMS)
    (EAST TO IN-THE-SCHOOL-FOYER)
    (FLAGS LIGHTBIT)>


<ROOM IN-THE-SICK-BAY
    (DESC "In the Sick Bay")
    (IN ROOMS)
    (WEST TO IN-THE-SCHOOL-FOYER)
    (FLAGS LIGHTBIT)>


<OBJECT UNNAMED-GIRL
    (IN IN-THE-SICK-BAY)
    (DESC "Unnamed Girl")
    (SYNONYM GIRL)
    (ADJECTIVE UNNAMED)
    (FLAGS TAKEBIT VOWELBIT)>


<ROOM IN-THE-MARBLE-STATEROOM
    (DESC "In the Marble Stateroom")
    (IN ROOMS)
    (NORTH TO IN-THE-SOUTH-HALL)
    (SOUTH TO IN-THE-SCHOOL-FOYER)
    (FLAGS LIGHTBIT)>


<OBJECT MAUREEN-SALLIS
    (IN IN-THE-MARBLE-STATEROOM)
    (DESC "Maureen Sallis")
    (SYNONYM SALLIS)
    (ADJECTIVE MAUREEN)
    (FLAGS TAKEBIT)>


<ROOM IN-THE-SOUTH-HALL
    (DESC "In the South Hall")
    (IN ROOMS)
    (NORTH TO IN-THE-GRAND-HALL)
    (SOUTH TO IN-THE-MARBLE-STATEROOM)
    (EAST TO IN-THE-SITTING-ROOM)
    (FLAGS LIGHTBIT)>


<ROOM IN-THE-SITTING-ROOM
    (DESC "In the Sitting Room")
    (IN ROOMS)
    (NORTH TO IN-THE-EASTERN-HALLWAY)
    (WEST TO IN-THE-SOUTH-HALL)
    (FLAGS LIGHTBIT)>


<OBJECT LUCINDA-PARKER
    (IN IN-THE-SITTING-ROOM)
    (DESC "Lucinda Parker")
    (SYNONYM PARKER)
    (ADJECTIVE LUCINDA)
    (FLAGS TAKEBIT)>


<ROOM IN-THE-EASTERN-HALLWAY
    (DESC "In the Eastern Hallway")
    (IN ROOMS)
    (NORTH TO IN-THE-WAITING-ROOM)
    (SOUTH TO IN-THE-SITTING-ROOM)
    (EAST TO IN-THE-DANCE-ROOM)
    (WEST TO IN-THE-GRAND-HALL)
    (FLAGS LIGHTBIT)>


<OBJECT MIA-FELLINI
    (IN IN-THE-EASTERN-HALLWAY)
    (DESC "Mia Fellini")
    (SYNONYM FELLINI)
    (ADJECTIVE MIA)
    (FLAGS TAKEBIT)>


<ROOM IN-THE-DANCE-ROOM
    (DESC "In the Dance Room")
    (IN ROOMS)
    (WEST TO IN-THE-EASTERN-HALLWAY)
    (FLAGS LIGHTBIT)>


<OBJECT THE-DANCER
    (IN IN-THE-DANCE-ROOM)
    (DESC "The Dancer")
    (SYNONYM DANCER)
    (ADJECTIVE THE)
    (FLAGS TAKEBIT)>


<ROOM IN-THE-WAITING-ROOM
    (DESC "In the Waiting Room")
    (IN ROOMS)
    (NORTH PER TRIZBORT-CONDITIONAL-EXIT)
    (SOUTH TO IN-THE-EASTERN-HALLWAY)
    (WEST TO IN-SCIENCE-LAB-1C)
    (FLAGS LIGHTBIT)>


<ROOM IN-SCIENCE-LAB-1C
    (DESC "In Science Lab 1C")
    (IN ROOMS)
    (SOUTH TO IN-THE-GRAND-HALL)
    (EAST TO IN-THE-WAITING-ROOM)
    (FLAGS LIGHTBIT)>


<ROOM IN-THE-GRAND-HALL
    (DESC "In the Grand Hall")
    (IN ROOMS)
    (NORTH TO IN-SCIENCE-LAB-1C)
    (SOUTH TO IN-THE-SOUTH-HALL)
    (EAST TO IN-THE-EASTERN-HALLWAY)
    (WEST TO IN-THE-SCHOOL-CHAPEL)
    (FLAGS LIGHTBIT)>


<OBJECT MADISON-JONES
    (IN IN-THE-GRAND-HALL)
    (DESC "Madison Jones")
    (SYNONYM JONES)
    (ADJECTIVE MADISON)
    (FLAGS TAKEBIT)>


<OBJECT KATE-SEUNG
    (IN IN-THE-GRAND-HALL)
    (DESC "Kate, Seung")
    (SYNONYM SEUNG)
    (ADJECTIVE KATE)
    (FLAGS TAKEBIT)>


<ROOM IN-THE-SCHOOL-CHAPEL
    (DESC "In the School Chapel")
    (IN ROOMS)
    (EAST TO IN-THE-GRAND-HALL)
    (FLAGS LIGHTBIT)>


<ROOM IN-THE-STAFF-LIBRARY
    (DESC "In the Staff Library")
    (IN ROOMS)
    (NORTH PER TRIZBORT-CONDITIONAL-EXIT)
    (SOUTH PER TRIZBORT-CONDITIONAL-EXIT)
    (FLAGS LIGHTBIT)>


<ROOM IN-THE-LEATHER-STUDY
    (DESC "In the Leather Study")
    (IN ROOMS)
    (SOUTH PER TRIZBORT-CONDITIONAL-EXIT)
    (EAST TO IN-THE-STRANGE-GALLERY)
    (WEST TO IN-A-CURTAINED-HALLWAY)
    (UP TO ON-THE-BALCONY)
    (FLAGS LIGHTBIT)>


<ROOM IN-THE-STRANGE-GALLERY
    (DESC "In the Strange Gallery")
    (IN ROOMS)
    (WEST TO IN-THE-LEATHER-STUDY)
    (FLAGS LIGHTBIT)>


<ROOM ON-THE-BALCONY
    (DESC "On the Balcony")
    (IN ROOMS)
    (DOWN TO IN-THE-LEATHER-STUDY)
    (FLAGS LIGHTBIT)>


<OBJECT WITCH
    (IN ON-THE-BALCONY)
    (DESC "Witch")
    (SYNONYM WITCH)
    (FLAGS TAKEBIT)>


<ROOM IN-A-CURTAINED-HALLWAY
    (DESC "In a Curtained Hallway")
    (IN ROOMS)
    (EAST TO IN-THE-LEATHER-STUDY)
    (WEST TO IN-A-CURTAINED-HALLWAY-2)
    (FLAGS LIGHTBIT)>


<ROOM IN-A-CURTAINED-HALLWAY-2
    (DESC "In a Curtained Hallway")
    (IN ROOMS)
    (EAST TO IN-A-CURTAINED-HALLWAY)
    (WEST TO AT-THE-OPULENT-CORNER)
    (FLAGS LIGHTBIT)>


<ROOM AT-THE-OPULENT-CORNER
    (DESC "At the Opulent Corner")
    (IN ROOMS)
    (NORTH TO BEFORE-THE-LEADLIGHT-DOOR)
    (EAST TO IN-A-CURTAINED-HALLWAY-2)
    (FLAGS LIGHTBIT)>


<OBJECT EVE-JOSHI
    (IN AT-THE-OPULENT-CORNER)
    (DESC "Eve Joshi")
    (SYNONYM JOSHI)
    (ADJECTIVE EVE)
    (FLAGS TAKEBIT VOWELBIT)>


<ROOM BEFORE-THE-LEADLIGHT-DOOR
    (DESC "Before the Leadlight Door")
    (IN ROOMS)
    (NORTH PER TRIZBORT-CONDITIONAL-EXIT)
    (SOUTH TO AT-THE-OPULENT-CORNER)
    (FLAGS LIGHTBIT)>


<ROOM object-2
    (DESC "???")
    (IN ROOMS)
    (NORTH TO IN-THE-FOUNDERS-ROOM)
    (SOUTH PER TRIZBORT-CONDITIONAL-EXIT)>


<ROOM IN-THE-FOUNDERS-ROOM
    (DESC "In the Founder's Room")
    (IN ROOMS)
    (SOUTH TO object-2)
    (EAST TO IN-THE-SECRET-PLACE)
    (FLAGS LIGHTBIT)>


<OBJECT FOUNDER
    (IN IN-THE-FOUNDERS-ROOM)
    (DESC "Founder")
    (SYNONYM FOUNDER)
    (FLAGS TAKEBIT)>


<ROOM IN-THE-SECRET-PLACE
    (DESC "In the Secret Place")
    (IN ROOMS)
    (WEST TO IN-THE-FOUNDERS-ROOM)
    (FLAGS LIGHTBIT)>


<OBJECT SHADOW
    (IN IN-THE-SECRET-PLACE)
    (DESC "Shadow")
    (SYNONYM SHADOW)
    (FLAGS TAKEBIT)>


<OBJECT FOUNDER2
    (IN IN-THE-SECRET-PLACE)
    (DESC "Founder")
    (SYNONYM FOUNDER)
    (FLAGS TAKEBIT)>


<ROOM IN-THE-UPSTAIRS-CHANGING-ROOM
    (DESC "In the Upstairs Changing Room")
    (IN ROOMS)
    (DOWN TO ON-THE-GYM-COURT-NORTH)
    (FLAGS LIGHTBIT)>


<OBJECT ISABELLE-GREEN
    (IN IN-THE-UPSTAIRS-CHANGING-ROOM)
    (DESC "Isabelle Green")
    (SYNONYM GREEN)
    (ADJECTIVE ISABELLE)
    (FLAGS TAKEBIT VOWELBIT)>

