"luster main file"

<VERSION ZIP>
<CONSTANT RELEASEID 1>

"Main Loop"

<CONSTANT GAME-BANNER "luster|An interactive fiction by A Trizbort User">

<ROUTINE GO ()
    <CRLF> <CRLF>
    <TELL "" CR CR>
    <V-VERSION> <CRLF>
    <SETG HERE ,FORK>
    <MOVE ,PLAYER ,HERE>
    <V-LOOK>
    <REPEAT ()
        <COND (<PARSER>
               <PERFORM ,PRSA ,PRSO ,PRSI>
               <COND (<NOT <GAME-VERB?>>
                      <APPLY <GETP ,HERE ,P?ACTION> ,M-END>
                      <CLOCKER>)>)>
        <SETG HERE <LOC ,WINNER>>>>

<INSERT-FILE "parser">

"Objects"

<ROOM FORK
    (DESC "Fork")
    (IN ROOMS)
    (NORTH TO TRAIN-CROSSING)
    (SOUTH TO MEANDERING-PATH)
    (WEST TO DIRT-PATH)
    (FLAGS LIGHTBIT)>


<OBJECT RETURN-FROM-PLAIN-TO-HERE
    (IN FORK)
    (DESC "Return from plain to here")
    (SYNONYM HERE)
    (ADJECTIVE RETURN FROM PLAIN TO)
    (FLAGS TAKEBIT)>


<ROOM TRAIN-CROSSING
    (DESC "Train Crossing")
    (IN ROOMS)
    (NORTH PER TRIZBORT-CONDITIONAL-EXIT)
    (SOUTH TO FORK)
    (FLAGS LIGHTBIT)>


<ROUTINE TRIZBORT-CONDITIONAL-EXIT ()
    <TELL "An export nymph appears on your keyboard. She says, 'You can't go that way, as that exit was marked as conditional, you know, a dotted line, in Trizbort. Obviously in your game you'll have a better rationale for this than, er, me.' She looks embarrassed. 'Bye!'" CR>
    <RFALSE>>


<ROOM DIRT-PATH
    (DESC "Dirt Path")
    (IN ROOMS)
    (SOUTH TO SHERIFF-STATION-ENTRANCE)
    (EAST TO FORK)
    (NE TO GATED-PATH)
    (NW TO LAKE-SHORE)
    (FLAGS LIGHTBIT)>


<ROOM SHERIFF-STATION-ENTRANCE
    (DESC "Sheriff Station Entrance")
    (IN ROOMS)
    (NORTH TO DIRT-PATH)
    (SOUTH PER TRIZBORT-CONDITIONAL-EXIT)
    (WEST TO POWER-ROOM)
    (IN TO SHERIFF-STATION)
    (FLAGS LIGHTBIT)>


<ROOM LAKE-SHORE
    (DESC "Lake Shore")
    (IN ROOMS)
    (SOUTH TO LAKE-SHORE-2)
    (SE TO DIRT-PATH)
    (FLAGS LIGHTBIT)>


<ROOM LAKE-SHORE-2
    (DESC "Lake Shore")
    (IN ROOMS)
    (NORTH TO LAKE-SHORE)
    (WEST TO DOCK)
    (FLAGS LIGHTBIT)>


<ROOM DOCK
    (DESC "Dock")
    (IN ROOMS)
    (EAST TO LAKE-SHORE-2)
    (WEST PER TRIZBORT-CONDITIONAL-EXIT)
    (FLAGS LIGHTBIT)>


<OBJECT RAFT
    (IN DOCK)
    (DESC "Raft")
    (SYNONYM RAFT)
    (FLAGS TAKEBIT)>


<ROOM LAKE-ON-RAFT
    (DESC "Lake (on raft)")
    (IN ROOMS)
    (EAST PER TRIZBORT-CONDITIONAL-EXIT)
    (FLAGS LIGHTBIT)>


<OBJECT BLUE-GEM-FALL-INTO-LAKE
    (IN LAKE-ON-RAFT)
    (DESC "Blue gem (fall into lake)")
    (SYNONYM LAKE)
    (ADJECTIVE BLUE GEM FALL INTO)
    (FLAGS TAKEBIT)>


<ROOM TEMPLE-ENTRANCE
    (DESC "Temple Entrance")
    (IN ROOMS)
    (WEST TO STATUE-ROOM-BECOMES-PLAIN)
    (FLAGS LIGHTBIT)>


<OBJECT BACK-TO-DOCK-ONCE-YOU-GET-GEM
    (IN TEMPLE-ENTRANCE)
    (DESC "(Back to dock once you get gem)")
    (SYNONYM GEM)
    (ADJECTIVE BACK TO DOCK ONCE YOU GET)
    (FLAGS TAKEBIT)>


<ROOM STATUE-ROOM-BECOMES-PLAIN
    (DESC "Statue Room (becomes plain)")
    (IN ROOMS)
    (NORTH TO SPECTATOR-BOX)
    (SOUTH TO ARMORY)
    (EAST TO TEMPLE-ENTRANCE)
    (WEST TO ARENA-ROOM)
    (FLAGS LIGHTBIT)>


<ROOM ARENA-ROOM
    (DESC "Arena Room")
    (IN ROOMS)
    (EAST TO STATUE-ROOM-BECOMES-PLAIN)
    (FLAGS LIGHTBIT)>


<OBJECT SWORDSMAN
    (IN ARENA-ROOM)
    (DESC "Swordsman")
    (SYNONYM SWORDSMAN)
    (FLAGS TAKEBIT)>


<ROOM SPECTATOR-BOX
    (DESC "Spectator Box")
    (IN ROOMS)
    (SOUTH TO STATUE-ROOM-BECOMES-PLAIN)
    (FLAGS LIGHTBIT)>


<OBJECT BALLPOINT-PEN
    (IN SPECTATOR-BOX)
    (DESC "Ballpoint pen")
    (SYNONYM PEN)
    (ADJECTIVE BALLPOINT)
    (FLAGS TAKEBIT)>


<ROOM ARMORY
    (DESC "Armory")
    (IN ROOMS)
    (NORTH TO STATUE-ROOM-BECOMES-PLAIN)
    (FLAGS LIGHTBIT)>


<ROOM GATED-PATH
    (DESC "Gated Path")
    (IN ROOMS)
    (NORTH TO BLANK-ROOM)
    (SW TO DIRT-PATH)
    (FLAGS LIGHTBIT)>


<ROOM BLANK-ROOM
    (DESC "Blank Room")
    (IN ROOMS)
    (NORTH TO OCEAN-ROOM)
    (SOUTH TO GATED-PATH)
    (EAST TO METALLIC-ROOM)
    (NE TO SPACE-ROOM)
    (NW TO RAIN-FOREST-ROOM)
    (FLAGS LIGHTBIT)>


<OBJECT LEVER-SWITCH-IT
    (IN BLANK-ROOM)
    (DESC "Lever (switch it)")
    (SYNONYM IT)
    (ADJECTIVE LEVER SWITCH)
    (FLAGS TAKEBIT)>


<ROOM OCEAN-ROOM
    (DESC "Ocean Room")
    (IN ROOMS)
    (SOUTH TO BLANK-ROOM)
    (FLAGS LIGHTBIT)>


<OBJECT PEDESTAL1
    (IN OCEAN-ROOM)
    (DESC "pedestal1")
    (SYNONYM PEDESTAL1)
    (FLAGS TAKEBIT)>


<OBJECT BLUE-GEM
    (IN OCEAN-ROOM)
    (DESC "(Blue gem)")
    (SYNONYM GEM)
    (ADJECTIVE BLUE)
    (FLAGS TAKEBIT)>


<ROOM RAIN-FOREST-ROOM
    (DESC "Rain-Forest Room")
    (IN ROOMS)
    (SE TO BLANK-ROOM)
    (FLAGS LIGHTBIT)>


<OBJECT PEDESTAL3
    (IN RAIN-FOREST-ROOM)
    (DESC "pedestal3")
    (SYNONYM PEDESTAL3)
    (FLAGS TAKEBIT)>


<OBJECT GREEN-GEM
    (IN RAIN-FOREST-ROOM)
    (DESC "(Green gem)")
    (SYNONYM GEM)
    (ADJECTIVE GREEN)
    (FLAGS TAKEBIT)>


<ROOM SPACE-ROOM
    (DESC "Space Room")
    (IN ROOMS)
    (SW TO BLANK-ROOM)
    (FLAGS LIGHTBIT)>


<OBJECT PEDESTAL2
    (IN SPACE-ROOM)
    (DESC "pedestal2")
    (SYNONYM PEDESTAL2)
    (FLAGS TAKEBIT)>


<OBJECT MIDNIGHT-GEM
    (IN SPACE-ROOM)
    (DESC "(Midnight gem)")
    (SYNONYM GEM)
    (ADJECTIVE MIDNIGHT)
    (FLAGS TAKEBIT)>


<ROOM METALLIC-ROOM
    (DESC "Metallic Room")
    (IN ROOMS)
    (WEST TO BLANK-ROOM)
    (FLAGS LIGHTBIT)>


<OBJECT PEDESTAL4
    (IN METALLIC-ROOM)
    (DESC "pedestal4")
    (SYNONYM PEDESTAL4)
    (FLAGS TAKEBIT)>


<OBJECT SILVER-GEM
    (IN METALLIC-ROOM)
    (DESC "(Silver gem)")
    (SYNONYM GEM)
    (ADJECTIVE SILVER)
    (FLAGS TAKEBIT)>


<ROOM MEANDERING-PATH
    (DESC "Meandering Path")
    (IN ROOMS)
    (NORTH TO FORK)
    (SOUTH TO DEAD-END)
    (WEST TO ROSARIO-ENTRANCE)
    (SE TO RAMEN-BOOTH)
    (NW TO ABAND-STORE-FRONT-MYERS-ENTRANCE)
    (FLAGS LIGHTBIT)>


<ROOM ABAND-STORE-FRONT-MYERS-ENTRANCE
    (DESC "Aband. Store Front Myers Entrance")
    (IN ROOMS)
    (WEST PER TRIZBORT-CONDITIONAL-EXIT)
    (SE TO MEANDERING-PATH)
    (FLAGS LIGHTBIT)>


<OBJECT MAT-STEEL-KEY
    (IN ABAND-STORE-FRONT-MYERS-ENTRANCE)
    (DESC "Mat (steel key)")
    (SYNONYM KEY)
    (ADJECTIVE MAT STEEL)
    (FLAGS TAKEBIT)>


<OBJECT MYERS-ENTRANCE
    (IN ABAND-STORE-FRONT-MYERS-ENTRANCE)
    (DESC "Myers Entrance")
    (SYNONYM ENTRANCE)
    (ADJECTIVE MYERS)
    (FLAGS TAKEBIT)>


<ROOM ABANDONED-SHOP
    (DESC "Abandoned Shop")
    (IN ROOMS)
    (EAST PER TRIZBORT-CONDITIONAL-EXIT)
    (FLAGS LIGHTBIT)>


<OBJECT CASH-REGISTERDIME
    (IN ABANDONED-SHOP)
    (DESC "Cash Register/Dime")
    (SYNONYM REGISTERDIME)
    (ADJECTIVE CASH)
    (FLAGS TAKEBIT)>


<ROOM ROSARIO-ENTRANCE
    (DESC "Rosario Entrance")
    (IN ROOMS)
    (EAST TO MEANDERING-PATH)
    (FLAGS LIGHTBIT)>


<ROOM DEAD-END
    (DESC "Dead End")
    (IN ROOMS)
    (NORTH TO MEANDERING-PATH)
    (SOUTH PER TRIZBORT-CONDITIONAL-EXIT)
    (FLAGS LIGHTBIT)>


<OBJECT RECTANGLE-PUT-MAT
    (IN DEAD-END)
    (DESC "Rectangle (put mat)")
    (SYNONYM MAT)
    (ADJECTIVE RECTANGLE PUT)
    (FLAGS TAKEBIT)>


<ROOM RAMEN-BOOTH
    (DESC "Ramen Booth")
    (IN ROOMS)
    (WEST PER TRIZBORT-CONDITIONAL-EXIT)
    (NW TO MEANDERING-PATH)
    (FLAGS LIGHTBIT)>


<ROOM INSIDE-RAMEN-BOOTH
    (DESC "Inside Ramen Booth")
    (IN ROOMS)
    (EAST PER TRIZBORT-CONDITIONAL-EXIT)
    (FLAGS LIGHTBIT)>


<OBJECT BULB-UNTIE-FROM-ROPE
    (IN INSIDE-RAMEN-BOOTH)
    (DESC "Bulb (untie from rope)")
    (SYNONYM ROPE)
    (ADJECTIVE BULB UNTIE FROM)
    (FLAGS TAKEBIT)>


<OBJECT NEED-STEEL-KEY
    (IN INSIDE-RAMEN-BOOTH)
    (DESC "Need steel key")
    (SYNONYM KEY)
    (ADJECTIVE NEED STEEL)
    (FLAGS TAKEBIT)>


<ROOM TIMBER-PATH
    (DESC "Timber Path")
    (IN ROOMS)
    (NORTH PER TRIZBORT-CONDITIONAL-EXIT)
    (SOUTH TO FOREST-MAZE)
    (FLAGS LIGHTBIT)>


<OBJECT NOTE
    (IN TIMBER-PATH)
    (DESC "Note:")
    (SYNONYM NOTE)
    (FLAGS TAKEBIT)>


<OBJECT -FOREST-ROOM-NAMES-ARE-RANDOM
    (IN TIMBER-PATH)
    (DESC "* forest room names are random.")
    (SYNONYM RANDOM)
    (ADJECTIVE OBJECT FOREST ROOM NAMES ARE)
    (FLAGS TAKEBIT)>


<OBJECT -LIGHT-GREEN-INDICATES-WRAPPING-MAZE
    (IN TIMBER-PATH)
    (DESC "* Light green indicates wrapping maze.")
    (SYNONYM MAZE)
    (ADJECTIVE OBJECT LIGHT GREEN INDICATES WRAPPING)
    (FLAGS TAKEBIT)>


<OBJECT -DIAGONAL-DIRECTIONS-ARE-POSSIBLE-BUT-IGNORED
    (IN TIMBER-PATH)
    (DESC "* Diagonal directions are possible but ignored.")
    (SYNONYM IGNORED)
    (ADJECTIVE OBJECT DIAGONAL DIRECTIONS ARE POSSIBLE BUT)
    (FLAGS TAKEBIT CONTBIT)>


<OBJECT WE-JUST-WANT-A-WAY-THROUGH
    (IN -DIAGONAL-DIRECTIONS-ARE-POSSIBLE-BUT-IGNORED)
    (DESC "We just want a way through.")
    (SYNONYM THROUGH)
    (ADJECTIVE WE JUST WANT A WAY)
    (FLAGS TAKEBIT)>


<ROOM FOREST-MAZE
    (DESC "Forest Maze")
    (IN ROOMS)
    (NORTH TO TIMBER-PATH)
    (SOUTH TO FOREST-MAZE-2)
    (FLAGS LIGHTBIT)>


<ROOM FOREST-MAZE-2
    (DESC "Forest Maze")
    (IN ROOMS)
    (NORTH TO FOREST-MAZE)
    (SOUTH TO FOREST-CENTER)
    (FLAGS LIGHTBIT)>


<ROOM FOREST-CENTER
    (DESC "Forest Center")
    (IN ROOMS)
    (NORTH TO FOREST-MAZE-2)
    (SOUTH TO FOREST-MAZE-6)
    (EAST TO FOREST-MAZE-8)
    (WEST TO FOREST-MAZE-3)
    (FLAGS LIGHTBIT)>


<ROOM FOREST-MAZE-3
    (DESC "Forest Maze")
    (IN ROOMS)
    (NORTH TO FOREST-MAZE-4)
    (SOUTH TO FOREST-MAZE-5)
    (EAST TO FOREST-CENTER)
    (WEST TO FOREST-MAZE-4)
    (FLAGS LIGHTBIT)>


<ROOM FOREST-MAZE-4
    (DESC "Forest Maze")
    (IN ROOMS)
    (SOUTH TO FOREST-MAZE-9)
    (EAST TO FOREST-MAZE-3)
    (WEST TO FOREST-CENTER-2)
    (FLAGS LIGHTBIT)>


<ROOM FOREST-CENTER-2
    (DESC "(Forest Center)")
    (IN ROOMS)
    (EAST TO FOREST-MAZE-4)
    (FLAGS LIGHTBIT)>


<ROOM FOREST-MAZE-5
    (DESC "Forest Maze")
    (IN ROOMS)
    (NORTH TO FOREST-MAZE-3)
    (SOUTH TO FOREST-MAZE-7)
    (FLAGS LIGHTBIT)>


<ROOM FOREST-MAZE-6
    (DESC "Forest Maze")
    (IN ROOMS)
    (NORTH TO FOREST-CENTER)
    (EAST TO CLEARING)
    (FLAGS LIGHTBIT)>


<ROOM CLEARING
    (DESC "Clearing")
    (IN ROOMS)
    (WEST TO FOREST-MAZE-6)
    (FLAGS LIGHTBIT)>


<OBJECT GREEN-GEM2
    (IN CLEARING)
    (DESC "Green Gem")
    (SYNONYM GEM)
    (ADJECTIVE GREEN)
    (FLAGS TAKEBIT)>


<ROOM FOREST-MAZE-7
    (DESC "Forest Maze")
    (IN ROOMS)
    (NORTH TO FOREST-MAZE-5)
    (SOUTH TO END-OF-CAVE)
    (FLAGS LIGHTBIT)>


<ROOM END-OF-CAVE
    (DESC "End of Cave")
    (IN ROOMS)
    (NORTH TO FOREST-MAZE-7)
    (FLAGS LIGHTBIT)>


<OBJECT MIDNIGHT-GEM-NEED-BULB
    (IN END-OF-CAVE)
    (DESC "Midnight Gem (need bulb)")
    (SYNONYM BULB)
    (ADJECTIVE MIDNIGHT GEM NEED)
    (FLAGS TAKEBIT)>


<ROOM FOREST-MAZE-8
    (DESC "(Forest Maze)")
    (IN ROOMS)
    (WEST TO FOREST-CENTER)
    (FLAGS LIGHTBIT)>


<ROOM SHERIFF-STATION
    (DESC "Sheriff Station")
    (IN ROOMS)
    (NORTH PER TRIZBORT-CONDITIONAL-EXIT)
    (WEST TO CRAMPED-BATHROOM)
    (FLAGS LIGHTBIT)>


<OBJECT NEED-COPPER-KEY-TO-EXIT
    (IN SHERIFF-STATION)
    (DESC "Need copper key to exit")
    (SYNONYM EXIT)
    (ADJECTIVE NEED COPPER KEY TO)
    (FLAGS TAKEBIT)>


<ROOM CRAMPED-BATHROOM
    (DESC "Cramped Bathroom")
    (IN ROOMS)
    (EAST TO SHERIFF-STATION)
    (FLAGS LIGHTBIT)>


<OBJECT SOAP-WASH-SOAP
    (IN CRAMPED-BATHROOM)
    (DESC "soap (wash soap)")
    (SYNONYM SOAP)
    (ADJECTIVE SOAP WASH)
    (FLAGS TAKEBIT)>


<ROOM FIELD
    (DESC "Field")
    (IN ROOMS)
    (SOUTH PER TRIZBORT-CONDITIONAL-EXIT)
    (FLAGS LIGHTBIT)>


<OBJECT CUBE-PUT-COIN-IN-SLOT
    (IN FIELD)
    (DESC "Cube (put coin in slot)")
    (SYNONYM SLOT)
    (ADJECTIVE CUBE PUT COIN IN)
    (FLAGS TAKEBIT)>


<OBJECT MAKES-SILVER-GEM
    (IN FIELD)
    (DESC "Makes silver gem")
    (SYNONYM GEM)
    (ADJECTIVE MAKES SILVER)
    (FLAGS TAKEBIT)>


<ROOM POWER-ROOM
    (DESC "Power Room")
    (IN ROOMS)
    (EAST TO SHERIFF-STATION-ENTRANCE)
    (FLAGS LIGHTBIT)>


<OBJECT SWITCH-BUTTONS-RBI
    (IN POWER-ROOM)
    (DESC "(switch buttons RBI)")
    (SYNONYM RBI)
    (ADJECTIVE SWITCH BUTTONS)
    (FLAGS TAKEBIT)>


<ROOM FOREST-MAZE-9
    (DESC "Forest Maze")
    (IN ROOMS)
    (NORTH TO FOREST-MAZE-4)
    (EAST TO FOREST-MAZE-4)
    (FLAGS LIGHTBIT)>


<ROOM TREE-CANOPY
    (DESC "Tree Canopy")
    (IN ROOMS)
    (FLAGS LIGHTBIT)>


<OBJECT FROMTO-CLEARING
    (IN TREE-CANOPY)
    (DESC "From/to clearing")
    (SYNONYM CLEARING)
    (ADJECTIVE FROMTO)
    (FLAGS TAKEBIT)>

