"Slasher Swamp map main file"

<VERSION ZIP>
<CONSTANT RELEASEID 1>

"Main Loop"

<CONSTANT GAME-BANNER "Slasher Swamp map|An interactive fiction by Andrew Schultz">

<ROUTINE GO ()
    <CRLF> <CRLF>
    <TELL "This is a map for Slasher Swamp, an IFComp 2014 entry. The dotted lines indicate places you need to search, and in what order." CR CR>
    <V-VERSION> <CRLF>
    <SETG HERE ,ROAD>
    <MOVE ,PLAYER ,HERE>
    <V-LOOK>
    <REPEAT ()
        <COND (<PARSER>
               <PERFORM ,PRSA ,PRSO ,PRSI>
               <COND (<NOT <GAME-VERB?>>
                      <APPLY <GETP ,HERE ,P?ACTION> ,M-END>
                      <CLOCKER>)>)>
        <SETG HERE <LOC ,WINNER>>>>

<INSERT-FILE "parser">

"Objects"

<ROOM ROAD
    (DESC "Road")
    (IN ROOMS)
    (SOUTH TO MUDDY-SWAMP)
    (FLAGS LIGHTBIT)>


<OBJECT TRUCK-1
    (IN ROAD)
    (DESC "TRUCK (1)")
    (SYNONYM 1)
    (ADJECTIVE TRUCK)
    (FLAGS TAKEBIT)>


<ROOM POND
    (DESC "Pond")
    (IN ROOMS)
    (EAST TO SWAMP-FOREST)
    (FLAGS LIGHTBIT)>


<ROOM MUDDY-SWAMP
    (DESC "Muddy Swamp")
    (IN ROOMS)
    (NORTH TO ROAD)
    (SOUTH TO ROTTING-WOODEN-WALKWAY)
    (EAST TO CONCRETE-BUILDING)
    (WEST TO MANGROVE-FOREST)
    (FLAGS LIGHTBIT)>


<ROOM EMPTY-FLORIDA-HIGHWAY
    (DESC "Empty Florida Highway")
    (IN ROOMS)
    (NORTH TO SWAMP-FOREST)
    (SOUTH TO CONCRETE-BUILDING)
    (EAST TO GRAVEL-ROAD)
    (FLAGS LIGHTBIT)>


<ROOM BLACKTOP-HIGHWAY
    (DESC "Blacktop Highway")
    (IN ROOMS)
    (SOUTH TO MANGROVE-FOREST)
    (WEST TO CREEPY-HIGHWAY)
    (FLAGS LIGHTBIT)>


<ROOM BAMBOO-FOREST
    (DESC "Bamboo Forest")
    (IN ROOMS)
    (NORTH TO DARK-GROVE)
    (WEST TO DRY-EVERGLADES)
    (FLAGS LIGHTBIT)>


<ROOM SWAMP-FOREST
    (DESC "Swamp Forest")
    (IN ROOMS)
    (NORTH PER TRIZBORT-CONDITIONAL-EXIT)
    (SOUTH TO EMPTY-FLORIDA-HIGHWAY)
    (EAST TO OAK-SWAMP)
    (WEST TO POND)
    (FLAGS LIGHTBIT)>


<ROUTINE TRIZBORT-CONDITIONAL-EXIT ()
    <TELL "An export nymph appears on your keyboard. She says, 'You can't go that way, as that exit was marked as conditional, you know, a dotted line, in Trizbort. Obviously in your game you'll have a better rationale for this than, er, me.' She looks embarrassed. 'Bye!'" CR>
    <RFALSE>>


<OBJECT BRIAR-PATCH-5
    (IN SWAMP-FOREST)
    (DESC "BRIAR PATCH (5)")
    (SYNONYM 5)
    (ADJECTIVE BRIAR PATCH)
    (FLAGS TAKEBIT)>


<ROOM DRY-EVERGLADES
    (DESC "Dry Everglades*")
    (IN ROOMS)
    (NORTH TO FRONT-PORCH)
    (SOUTH TO CREEPY-HIGHWAY)
    (EAST TO BAMBOO-FOREST)
    (WEST TO PALMETTO-FLAT)
    (FLAGS LIGHTBIT)>


<ROOM DARK-GROVE
    (DESC "Dark Grove*")
    (IN ROOMS)
    (NORTH TO SOUTH-BANK-OF-A-BAYOU)
    (SOUTH TO BAMBOO-FOREST)
    (FLAGS LIGHTBIT)>


<OBJECT E-TO-SWAMP-FOREST
    (IN DARK-GROVE)
    (DESC "E to swamp forest")
    (SYNONYM FOREST)
    (ADJECTIVE E TO SWAMP)
    (FLAGS TAKEBIT VOWELBIT)>


<ROOM CREEPY-HIGHWAY
    (DESC "Creepy Highway")
    (IN ROOMS)
    (NORTH TO DRY-EVERGLADES)
    (SOUTH TO SCRUB-FOREST)
    (EAST TO BLACKTOP-HIGHWAY)
    (WEST TO DESOLATE-HIGHWAY)
    (FLAGS LIGHTBIT)>


<ROOM MANGROVE-FOREST
    (DESC "Mangrove Forest")
    (IN ROOMS)
    (NORTH TO BLACKTOP-HIGHWAY)
    (EAST TO MUDDY-SWAMP)
    (WEST TO SCRUB-FOREST)
    (FLAGS LIGHTBIT)>


<ROOM DESOLATE-HIGHWAY
    (DESC "Desolate Highway")
    (IN ROOMS)
    (NORTH TO PALMETTO-FLAT)
    (SOUTH TO PINE-FLATWOOD)
    (EAST TO CREEPY-HIGHWAY)
    (FLAGS LIGHTBIT)>


<ROOM SCRUB-FOREST
    (DESC "Scrub Forest")
    (IN ROOMS)
    (NORTH TO CREEPY-HIGHWAY)
    (EAST TO MANGROVE-FOREST)
    (WEST TO PINE-FLATWOOD)
    (FLAGS LIGHTBIT)>


<ROOM PINE-FLATWOOD
    (DESC "Pine Flatwood*")
    (IN ROOMS)
    (NORTH TO DESOLATE-HIGHWAY)
    (EAST TO SCRUB-FOREST)
    (FLAGS LIGHTBIT)>


<OBJECT WS-TO-SWAMP
    (IN PINE-FLATWOOD)
    (DESC "W/S to swamp")
    (SYNONYM SWAMP)
    (ADJECTIVE WS TO)
    (FLAGS TAKEBIT)>


<ROOM ROTTING-WOODEN-WALKWAY
    (DESC "Rotting Wooden Walkway")
    (IN ROOMS)
    (NORTH TO MUDDY-SWAMP)
    (SOUTH TO SANDY-GRASS)
    (FLAGS LIGHTBIT)>


<ROOM CONCRETE-BUILDING
    (DESC "Concrete Building")
    (IN ROOMS)
    (NORTH TO EMPTY-FLORIDA-HIGHWAY)
    (SOUTH TO DARK-CONCRETE-BUILDING)
    (EAST TO CONCRETE-SLAB)
    (WEST TO MUDDY-SWAMP)
    (FLAGS LIGHTBIT)>


<ROOM SANDY-GRASS
    (DESC "Sandy Grass")
    (IN ROOMS)
    (NORTH TO ROTTING-WOODEN-WALKWAY)
    (SOUTH TO DUSTY-CLEARING)
    (EAST TO DUSTY-CLEARING)
    (WEST TO GAZEBO)
    (FLAGS LIGHTBIT)>


<OBJECT KING-OF-SPADES
    (IN SANDY-GRASS)
    (DESC "King of Spades")
    (SYNONYM SPADES)
    (ADJECTIVE KING OF)
    (FLAGS TAKEBIT)>


<ROOM GAZEBO
    (DESC "Gazebo")
    (IN ROOMS)
    (EAST TO SANDY-GRASS)
    (FLAGS LIGHTBIT)>


<OBJECT QUEEN-OF-CLUBS
    (IN GAZEBO)
    (DESC "Queen of Clubs")
    (SYNONYM CLUBS)
    (ADJECTIVE QUEEN OF)
    (FLAGS TAKEBIT)>


<ROOM DUSTY-CLEARING
    (DESC "Dusty Clearing")
    (IN ROOMS)
    (NORTH TO SANDY-GRASS)
    (EAST TO GATE)
    (FLAGS LIGHTBIT)>


<ROOM GATE
    (DESC "Gate")
    (IN ROOMS)
    (EAST TO GARDEN)
    (WEST TO DUSTY-CLEARING)
    (FLAGS LIGHTBIT)>


<ROOM GARDEN
    (DESC "Garden")
    (IN ROOMS)
    (NORTH TO GARDEN-2)
    (EAST TO CONCRETE-RUINS)
    (WEST TO GATE)
    (FLAGS LIGHTBIT)>


<ROOM CONCRETE-RUINS
    (DESC "Concrete Ruins")
    (IN ROOMS)
    (NORTH TO ROSE-BUSH)
    (WEST TO GARDEN)
    (FLAGS LIGHTBIT)>


<OBJECT JACK-OF-SPADES
    (IN CONCRETE-RUINS)
    (DESC "Jack of Spades")
    (SYNONYM SPADES)
    (ADJECTIVE JACK OF)
    (FLAGS TAKEBIT)>


<ROOM ROSE-BUSH
    (DESC "Rose Bush")
    (IN ROOMS)
    (SOUTH TO CONCRETE-RUINS)
    (WEST TO GARDEN-2)
    (FLAGS LIGHTBIT)>


<ROOM GARDEN-2
    (DESC "Garden")
    (IN ROOMS)
    (SOUTH TO GARDEN)
    (EAST TO ROSE-BUSH)
    (FLAGS LIGHTBIT)>


<ROOM DARK-CONCRETE-BUILDING
    (DESC "Dark Concrete Building")
    (IN ROOMS)
    (NORTH TO CONCRETE-BUILDING)>


<OBJECT DEER-DOLL-HEAD
    (IN DARK-CONCRETE-BUILDING)
    (DESC "Deer (doll head)")
    (SYNONYM HEAD)
    (ADJECTIVE DEER DOLL)
    (FLAGS TAKEBIT)>


<ROOM CONCRETE-SLAB
    (DESC "Concrete Slab")
    (IN ROOMS)
    (NORTH TO GRAVEL-ROAD)
    (SOUTH TO GRAVEYARD)
    (EAST TO BUSH-THICKET)
    (WEST TO CONCRETE-BUILDING)
    (FLAGS LIGHTBIT)>


<ROOM GRAVEL-ROAD
    (DESC "Gravel Road")
    (IN ROOMS)
    (NORTH TO OAK-SWAMP)
    (SOUTH TO BUSH-THICKET)
    (EAST TO GAS-STATION-PARKING-LOT)
    (WEST TO EMPTY-FLORIDA-HIGHWAY)
    (FLAGS LIGHTBIT)>


<ROOM BUSH-THICKET
    (DESC "Bush Thicket")
    (IN ROOMS)
    (NORTH TO GRAVEL-ROAD)
    (EAST TO MEADOW)
    (WEST TO CONCRETE-SLAB)
    (FLAGS LIGHTBIT)>


<OBJECT S-TO-SWAMP-FOREST
    (IN BUSH-THICKET)
    (DESC "S to Swamp Forest")
    (SYNONYM FOREST)
    (ADJECTIVE S TO SWAMP)
    (FLAGS TAKEBIT)>


<ROOM OAK-SWAMP
    (DESC "Oak Swamp")
    (IN ROOMS)
    (NORTH TO SWAMP-CLEARING-E-TO-GRASS-FIELD)
    (SOUTH TO GRAVEL-ROAD)
    (WEST TO SWAMP-FOREST)
    (FLAGS LIGHTBIT)>


<OBJECT E-TO-SWAMP-FOREST2
    (IN OAK-SWAMP)
    (DESC "E to Swamp Forest")
    (SYNONYM FOREST)
    (ADJECTIVE E TO SWAMP)
    (FLAGS TAKEBIT VOWELBIT)>


<ROOM PALMETTO-FLAT
    (DESC "Palmetto Flat")
    (IN ROOMS)
    (NORTH TO DUSTY-HILL)
    (SOUTH TO DESOLATE-HIGHWAY)
    (EAST TO DRY-EVERGLADES)
    (FLAGS LIGHTBIT)>


<OBJECT W-TO-SWAMP-FOREST
    (IN PALMETTO-FLAT)
    (DESC "W to Swamp Forest")
    (SYNONYM FOREST)
    (ADJECTIVE W TO SWAMP)
    (FLAGS TAKEBIT)>


<ROOM DUSTY-HILL
    (DESC "Dusty Hill*")
    (IN ROOMS)
    (NORTH TO SOUTH-BANK-OF-A-BAYOU)
    (SOUTH TO PALMETTO-FLAT)
    (FLAGS LIGHTBIT)>


<ROOM FRONT-PORCH
    (DESC "Front Porch")
    (IN ROOMS)
    (NORTH TO LIVING-ROOM)
    (SOUTH TO DRY-EVERGLADES)
    (FLAGS LIGHTBIT)>


<ROOM LIVING-ROOM
    (DESC "Living Room")
    (IN ROOMS)
    (NORTH TO KITCHEN)
    (SOUTH TO FRONT-PORCH)>


<ROOM KITCHEN
    (DESC "Kitchen")
    (IN ROOMS)
    (NORTH TO SOUTH-BANK-OF-A-BAYOU)
    (SOUTH TO LIVING-ROOM)
    (FLAGS LIGHTBIT)>


<OBJECT SINK-2
    (IN KITCHEN)
    (DESC "SINK (2)")
    (SYNONYM 2)
    (ADJECTIVE SINK)
    (FLAGS TAKEBIT)>


<ROOM SOUTH-BANK-OF-A-BAYOU
    (DESC "South Bank of a Bayou*")
    (IN ROOMS)
    (SOUTH TO KITCHEN)
    (EAST TO DARK-GROVE)
    (WEST TO DUSTY-HILL)
    (FLAGS LIGHTBIT)>


<ROOM MEADOW
    (DESC "Meadow*")
    (IN ROOMS)
    (NORTH TO GRAVEL-ROAD)
    (SOUTH TO PALMETTO-CLEARING)
    (FLAGS LIGHTBIT)>


<ROOM SWAMP-CLEARING-E-TO-GRASS-FIELD
    (DESC "Swamp Clearing (E to grass field)")
    (IN ROOMS)
    (SOUTH TO OAK-SWAMP)
    (FLAGS LIGHTBIT)>


<OBJECT NW-TO-SWAMP-FOREST
    (IN SWAMP-CLEARING-E-TO-GRASS-FIELD)
    (DESC "N/W to Swamp Forest")
    (SYNONYM FOREST)
    (ADJECTIVE NW TO SWAMP)
    (FLAGS TAKEBIT)>


<ROOM PALMETTO-CLEARING
    (DESC "Palmetto Clearing")
    (IN ROOMS)
    (NORTH TO MEADOW)
    (SOUTH PER TRIZBORT-CONDITIONAL-EXIT)
    (FLAGS LIGHTBIT)>


<OBJECT WE-TO-SWAMP-FOREST
    (IN PALMETTO-CLEARING)
    (DESC "W/E to Swamp Forest")
    (SYNONYM FOREST)
    (ADJECTIVE WE TO SWAMP)
    (FLAGS TAKEBIT)>


<ROOM PALMETTO-FIELD
    (DESC "Palmetto Field")
    (IN ROOMS)
    (NORTH PER TRIZBORT-CONDITIONAL-EXIT)
    (SOUTH PER TRIZBORT-CONDITIONAL-EXIT)
    (FLAGS LIGHTBIT)>


<OBJECT WE-TO-SWAMP-FOREST2
    (IN PALMETTO-FIELD)
    (DESC "W/E to Swamp Forest")
    (SYNONYM FOREST)
    (ADJECTIVE WE TO SWAMP)
    (FLAGS TAKEBIT)>


<ROOM IN-FRONT-OF-A-STRAW-HUT
    (DESC "In Front of a Straw Hut")
    (IN ROOMS)
    (NORTH PER TRIZBORT-CONDITIONAL-EXIT)
    (SOUTH PER TRIZBORT-CONDITIONAL-EXIT)
    (FLAGS LIGHTBIT)>


<ROOM STRAW-HUT
    (DESC "Straw Hut")
    (IN ROOMS)
    (NORTH PER TRIZBORT-CONDITIONAL-EXIT)
    (FLAGS LIGHTBIT)>


<OBJECT SHACK11
    (IN STRAW-HUT)
    (DESC "SHACK(11)")
    (SYNONYM SHACK11)
    (FLAGS TAKEBIT)>


<OBJECT NEED-SEVERED-HEAD-AND-REVOLVER-NOT-MAN-WREVOLVER
    (IN STRAW-HUT)
    (DESC "Need severed head and revolver (not man w/revolver)")
    (SYNONYM WREVOLVER)
    (ADJECTIVE NEED SEVERED HEAD AND REVOLVER NOT MAN)
    (FLAGS TAKEBIT)>


<ROOM PINE-FOREST
    (DESC "Pine Forest")
    (IN ROOMS)
    (NORTH TO PINE-FOREST-2)
    (SOUTH PER TRIZBORT-CONDITIONAL-EXIT)
    (EAST TO PINE-FOREST-6)
    (FLAGS LIGHTBIT)>


<ROOM PINE-FOREST-2
    (DESC "Pine Forest")
    (IN ROOMS)
    (NORTH TO PINE-FOREST-3)
    (SOUTH TO PINE-FOREST)
    (EAST TO PINE-FOREST-5)
    (FLAGS LIGHTBIT)>


<ROOM PINE-FOREST-3
    (DESC "Pine Forest")
    (IN ROOMS)
    (SOUTH TO PINE-FOREST-2)
    (EAST TO PINE-FOREST-4)
    (FLAGS LIGHTBIT)>


<ROOM PINE-FOREST-4
    (DESC "Pine Forest")
    (IN ROOMS)
    (SOUTH TO PINE-FOREST-5)
    (EAST TO PINE-FOREST-9)
    (WEST TO PINE-FOREST-3)
    (FLAGS LIGHTBIT)>


<ROOM PINE-FOREST-5
    (DESC "Pine Forest")
    (IN ROOMS)
    (NORTH TO PINE-FOREST-4)
    (SOUTH TO PINE-FOREST-6)
    (EAST TO PINE-FOREST-8)
    (WEST TO PINE-FOREST-2)
    (FLAGS LIGHTBIT)>


<ROOM PINE-FOREST-6
    (DESC "Pine Forest")
    (IN ROOMS)
    (NORTH TO PINE-FOREST-5)
    (EAST TO PINE-FOREST-7)
    (WEST TO PINE-FOREST)
    (FLAGS LIGHTBIT)>


<ROOM PINE-FOREST-7
    (DESC "Pine Forest")
    (IN ROOMS)
    (NORTH TO PINE-FOREST-8)
    (WEST TO PINE-FOREST-6)
    (FLAGS LIGHTBIT)>


<ROOM PINE-FOREST-8
    (DESC "Pine Forest")
    (IN ROOMS)
    (NORTH TO PINE-FOREST-9)
    (SOUTH TO PINE-FOREST-7)
    (WEST TO PINE-FOREST-5)
    (FLAGS LIGHTBIT)>


<ROOM PINE-FOREST-9
    (DESC "Pine Forest")
    (IN ROOMS)
    (SOUTH TO PINE-FOREST-8)
    (EAST TO IN-FRONT-OF-SHACK)
    (WEST TO PINE-FOREST-4)
    (FLAGS LIGHTBIT)>


<ROOM IN-FRONT-OF-SHACK
    (DESC "In Front of Shack")
    (IN ROOMS)
    (NORTH TO IN-SHACK)
    (WEST TO PINE-FOREST-9)
    (FLAGS LIGHTBIT)>


<ROOM IN-SHACK
    (DESC "In Shack")
    (IN ROOMS)
    (NORTH TO ALTAR)
    (SOUTH TO IN-FRONT-OF-SHACK)
    (FLAGS LIGHTBIT)>


<ROOM ALTAR
    (DESC "Altar")
    (IN ROOMS)
    (SOUTH TO IN-SHACK)
    (WEST PER TRIZBORT-CONDITIONAL-EXIT)
    (FLAGS LIGHTBIT)>


<OBJECT ALTAR-6-BODY-7
    (IN ALTAR)
    (DESC "ALTAR (6), BODY (7)")
    (SYNONYM 7)
    (ADJECTIVE ALTAR 6 BODY)
    (FLAGS TAKEBIT VOWELBIT)>


<ROOM GRAVEYARD
    (DESC "Graveyard")
    (IN ROOMS)
    (NORTH TO CONCRETE-SLAB)
    (FLAGS LIGHTBIT)>


<OBJECT GRAVE-9-NEED-SHOVEL
    (IN GRAVEYARD)
    (DESC "GRAVE (9) (need shovel)")
    (SYNONYM SHOVEL)
    (ADJECTIVE GRAVE 9 NEED)
    (FLAGS TAKEBIT)>


<OBJECT COFFIN-WIRON-KEY-MAN10
    (IN GRAVEYARD)
    (DESC "COFFIN w/iron key, MAN(10)")
    (SYNONYM MAN10)
    (ADJECTIVE COFFIN WIRON KEY)
    (FLAGS TAKEBIT)>


<ROOM GAS-STATION-PARKING-LOT
    (DESC "Gas Station Parking Lot")
    (IN ROOMS)
    (NORTH TO ALLEY-NORTH-OF-GAS-STATION)
    (SOUTH TO SOUTH-OF-THE-GAS-STATION)
    (EAST TO INSIDE-GAS-STATION)
    (WEST TO GRAVEL-ROAD)
    (FLAGS LIGHTBIT)>


<ROOM ALLEY-NORTH-OF-GAS-STATION
    (DESC "Alley North of Gas Station")
    (IN ROOMS)
    (EAST TO GAS-STATION-DUMPSTER)
    (WEST TO GAS-STATION-PARKING-LOT)
    (FLAGS LIGHTBIT)>


<ROOM SOUTH-OF-THE-GAS-STATION
    (DESC "South of the Gas Station")
    (IN ROOMS)
    (EAST TO GAS-STATION-DUMPSTER)
    (WEST TO GAS-STATION-PARKING-LOT)
    (FLAGS LIGHTBIT)>


<ROOM GAS-STATION-DUMPSTER
    (DESC "Gas Station Dumpster")
    (IN ROOMS)
    (NORTH TO ALLEY-NORTH-OF-GAS-STATION)
    (SOUTH TO SOUTH-OF-THE-GAS-STATION)
    (FLAGS LIGHTBIT)>


<OBJECT DUMPSTER-3
    (IN GAS-STATION-DUMPSTER)
    (DESC "DUMPSTER (3)")
    (SYNONYM 3)
    (ADJECTIVE DUMPSTER)
    (FLAGS TAKEBIT)>


<OBJECT E-SWAMP-FOREST
    (IN GAS-STATION-DUMPSTER)
    (DESC "E: Swamp Forest")
    (SYNONYM FOREST)
    (ADJECTIVE E SWAMP)
    (FLAGS TAKEBIT VOWELBIT)>


<ROOM INSIDE-GAS-STATION
    (DESC "Inside Gas Station")
    (IN ROOMS)
    (NORTH PER TRIZBORT-CONDITIONAL-EXIT)
    (WEST TO GAS-STATION-PARKING-LOT)
    (FLAGS LIGHTBIT)>


<OBJECT GARBAGE
    (IN INSIDE-GAS-STATION)
    (DESC "GARBAGE")
    (SYNONYM GARBAGE)
    (FLAGS TAKEBIT)>


<ROOM GAS-STATION-OFFICE
    (DESC "Gas Station Office")
    (IN ROOMS)
    (SOUTH PER TRIZBORT-CONDITIONAL-EXIT)>


<OBJECT BLANKET-4
    (IN GAS-STATION-OFFICE)
    (DESC "BLANKET (4)")
    (SYNONYM 4)
    (ADJECTIVE BLANKET)
    (FLAGS TAKEBIT)>


<ROOM SHRINE
    (DESC "Shrine")
    (IN ROOMS)
    (EAST PER TRIZBORT-CONDITIONAL-EXIT)>


<OBJECT HEAD-NEEDED-TO-WIN
    (IN SHRINE)
    (DESC "Head (needed to win)")
    (SYNONYM WIN)
    (ADJECTIVE HEAD NEEDED TO)
    (FLAGS TAKEBIT)>


<ROOM GRASS-FIELD
    (DESC "Grass Field")
    (IN ROOMS)
    (NORTH TO CLOVER-FIELD)
    (SOUTH TO SUNFLOWER-FIELD)
    (WEST TO FLOWER-FIELD)
    (FLAGS LIGHTBIT)>


<OBJECT W-TO-FLOWER
    (IN GRASS-FIELD)
    (DESC "(W to flower)")
    (SYNONYM FLOWER)
    (ADJECTIVE W TO)
    (FLAGS TAKEBIT)>


<ROOM CLOVER-FIELD
    (DESC "Clover Field")
    (IN ROOMS)
    (SOUTH TO MUCK-FIELD)
    (EAST TO FLOWER-FIELD)
    (WEST TO GRASS-FIELD)
    (FLAGS LIGHTBIT)>


<OBJECT N-TO-SWAMP
    (IN CLOVER-FIELD)
    (DESC "N to Swamp")
    (SYNONYM SWAMP)
    (ADJECTIVE N TO)
    (FLAGS TAKEBIT)>


<ROOM MUCK-FIELD
    (DESC "Muck Field")
    (IN ROOMS)
    (NORTH TO IN-FRONT-OF-AN-OUTHOUSE)
    (SOUTH TO FLOWER-FIELD)
    (EAST TO MUCK-FIELD)
    (WEST TO CLOVER-FIELD)
    (FLAGS LIGHTBIT)>


<OBJECT E-TO-GRASS
    (IN MUCK-FIELD)
    (DESC "(E to grass)")
    (SYNONYM GRASS)
    (ADJECTIVE E TO)
    (FLAGS TAKEBIT)>


<ROOM SUNFLOWER-FIELD
    (DESC "Sunflower Field")
    (IN ROOMS)
    (NORTH TO GRASS-FIELD)
    (SOUTH TO FLOWER-FIELD)
    (EAST TO FLOWER-FIELD)
    (WEST TO SUNFLOWER-FIELD)
    (FLAGS LIGHTBIT)>


<ROOM FLOWER-FIELD
    (DESC "Flower Field")
    (IN ROOMS)
    (SOUTH TO CLOVER-FIELD)
    (EAST TO MUCK-FIELD)
    (WEST TO SUNFLOWER-FIELD)
    (FLAGS LIGHTBIT)>


<OBJECT W-TO-GRASS
    (IN FLOWER-FIELD)
    (DESC "(W to grass)")
    (SYNONYM GRASS)
    (ADJECTIVE W TO)
    (FLAGS TAKEBIT)>


<ROOM IN-FRONT-OF-AN-OUTHOUSE
    (DESC "In Front of an Outhouse")
    (IN ROOMS)
    (NORTH TO OUTHOUSE)
    (SOUTH TO MUCK-FIELD)
    (FLAGS LIGHTBIT)>


<ROOM OUTHOUSE
    (DESC "Outhouse")
    (IN ROOMS)
    (SOUTH TO IN-FRONT-OF-AN-OUTHOUSE)
    (FLAGS LIGHTBIT)>


<OBJECT HOLE-8
    (IN OUTHOUSE)
    (DESC "HOLE (8)")
    (SYNONYM 8)
    (ADJECTIVE HOLE)
    (FLAGS TAKEBIT)>


<ROOM SWAMP-1-FROM-VARIOUS-LOCATIONS
    (DESC "Swamp-1 (from various locations)")
    (IN ROOMS)
    (SOUTH TO SWAMP-2-FROM-VARIOUS-LOCATIONS)
    (FLAGS LIGHTBIT)>


<OBJECT NORTH-TO
    (IN SWAMP-1-FROM-VARIOUS-LOCATIONS)
    (DESC "North to")
    (SYNONYM TO)
    (ADJECTIVE NORTH)
    (FLAGS TAKEBIT)>


<OBJECT DESOLATE-HIGHWAY2
    (IN SWAMP-1-FROM-VARIOUS-LOCATIONS)
    (DESC "Desolate Highway")
    (SYNONYM HIGHWAY)
    (ADJECTIVE DESOLATE)
    (FLAGS TAKEBIT)>


<ROOM SWAMP-2-FROM-VARIOUS-LOCATIONS
    (DESC "Swamp-2 (from various locations)")
    (IN ROOMS)
    (SOUTH TO SWAMP-3)
    (FLAGS LIGHTBIT)>


<OBJECT ALWAYS-TO
    (IN SWAMP-2-FROM-VARIOUS-LOCATIONS)
    (DESC "Always to")
    (SYNONYM TO)
    (ADJECTIVE ALWAYS)
    (FLAGS TAKEBIT VOWELBIT)>


<OBJECT SWAMP-32
    (IN SWAMP-2-FROM-VARIOUS-LOCATIONS)
    (DESC "Swamp-3")
    (SYNONYM SWAMP-3)
    (FLAGS TAKEBIT)>


<ROOM SWAMP-3
    (DESC "Swamp-3")
    (IN ROOMS)
    (SOUTH TO POND)
    (FLAGS LIGHTBIT)>


<OBJECT SOUTH-TO-POND-OTHERWISE-TO-SWAMP-2
    (IN SWAMP-3)
    (DESC "South to Pond, Otherwise to Swamp-2")
    (SYNONYM SWAMP-2)
    (ADJECTIVE SOUTH TO POND OTHERWISE TO)
    (FLAGS TAKEBIT)>

